# reporter: json
use_nested_configs: true
disabled_rules:
  - todo # 開発中のみignore
  - trailing_whitespace
  - colon
  - comma
  - cyclomatic_complexity
  - function_parameter_count
  - conditional_binding_cascade
  - legacy_cggeometry_functions
excluded:
  - Carthage
  - Pods
line_length: 150
function_body_length: 800
type_body_length:
 - 1000 #warning
 - 900 #error
file_length:
  warning: 1100
  error: 1200
variable_name:
  excluded: # excluded via string array
    - id
